import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { WelcomeToast } from '../components/common/welcome-toast'
import { ReactNode } from 'react'
import { cn } from '@/lib/utils'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const revalidate = 86400 // One day (ISR)

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn('bg-gray-900 text-white antialiased', inter.className)}>
        {children}
        <Toaster closeButton />
        <WelcomeToast />
      </body>
    </html>
  )
}
